name: "Simple Build"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 20.x
          cache: "npm"
          
      - name: Install dependencies
        run: |
          npm install --no-optional
          npm uninstall sharp
          
      - name: Create environment files
        run: |
          echo "NODE_ENV=production" > .env.production
          echo "PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" >> .env.production
          echo "CLERK_FRONTEND_API=${{ secrets.CLERK_FRONTEND_API }}" >> .env.production
          echo "PLASMO_PUBLIC_API_URL=${{ secrets.API_URL }}" >> .env.production
          echo "PLASMO_PUBLIC_CLERK_SYNC_HOST=${{ secrets.CLERK_SYNC_HOST }}" >> .env.production
          echo "CRX_PUBLIC_KEY=${{ secrets.CRX_PUBLIC_KEY }}" > .env.chrome
          echo "CRX_ID=${{ secrets.CRX_ID }}" >> .env.chrome
        
      - name: Build extension (Chrome only)
        run: |
          export NODE_OPTIONS=--max_old_space_size=8192
          npx plasmo build --no-minify --env-file=.env.production --env-file=.env.chrome
        
      - name: Package extension
        run: npx plasmo package
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension
          path: build/chrome-mv3-prod.zip
          if-no-files-found: warn 