name: "Submit to Web Store"
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          cache: "npm"
      - name: Install dependencies
        run: npm install
      - name: Build the extension
        run: npm run build
      - name: Package the extension into a zip artifact
        run: npm run package
      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
