name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 20.x
          cache: "npm"
          
      - name: Install dependencies
        run: npm install
        
      - name: Create environment files
        run: |
          echo "NODE_ENV=development" > .env.development
          echo "PLASMO_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.CLERK_PUBLISHABLE_KEY }}" >> .env.development
          echo "CLERK_FRONTEND_API=${{ secrets.CLERK_FRONTEND_API }}" >> .env.development
          echo "PLASMO_PUBLIC_API_URL=${{ secrets.API_URL }}" >> .env.development
          echo "PLASMO_PUBLIC_CLERK_SYNC_HOST=${{ secrets.CLERK_SYNC_HOST }}" >> .env.development
          echo "CRX_PUBLIC_KEY=${{ secrets.CRX_PUBLIC_KEY }}" > .env.chrome
          echo "CRX_ID=${{ secrets.CRX_ID }}" >> .env.chrome
        
      # Uncomment when you add tests to your project
      # - name: Run tests
      #   run: |
      #     export NODE_OPTIONS=--max_old_space_size=8192
      #     npm test 