name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 16.x
          cache: "npm"
          
      - name: Install dependencies
        run: npm install
        
      # Uncomment when you add tests to your project
      # - name: Run tests
      #   run: npm test 